Repository starknet-io/starknet.js, pull requests merged in 2021-11, with the labels that each got.

#39 fix: package-lock release
  .releaserc
  package-lock.json
Labels: bug

#41 fix: export needed types
  src/ellipticalCurve.ts
Labels: bug

#42 Release 1.5.2
  .releaserc
  CHANGELOG.md
  package-lock.json
  package.json
  src/ellipticalCurve.ts
  src/starknet.ts
Labels: release

#44 Release 1.5.3
  src/contract.ts
Labels: release

#51 Introduce Provider and Signer
  README.md
  __tests__/account.test.ts
  __tests__/contract.test.ts
  __tests__/provider.test.ts
  __tests__/signer.test.ts
  __tests__/utils/__snapshots__/ellipticalCurve.test.ts.snap
  __tests__/utils/__snapshots__/utils.browser.test.ts.snap
  __tests__/utils/__snapshots__/utils.test.ts.snap
  __tests__/utils/ellipticalCurve.test.ts
  __tests__/utils/utils.browser.test.ts
  __tests__/utils/utils.test.ts
  package.json
  src/contract.ts
  src/index.ts
  src/provider/default.ts
  src/provider/index.ts
  src/provider/interface.ts
  src/signer/default.ts
  src/signer/index.ts
  src/signer/interface.ts
  src/starknet.ts
  src/types.ts
  src/utils/ellipticCurve.ts
  src/utils/hash.ts
  src/utils/index.ts
  src/utils/stark.ts
  src/wallet.ts
Labels: enhancement, MAJOR

#54 fix: msgHash length check fix in signature verify function
  __tests__/ellipticalCurve.test.ts
  src/ellipticalCurve.ts
Labels: bug

#57 feat: add computeHashOnElements
  __tests__/utils/utils.test.ts
  src/utils/stark.ts
Labels: enhancement

#61 feat: alpha 4
  __mocks__/ArgentAccount.json
  __mocks__/ERC20.json
  __mocks__/Readme.md
  __tests__/account.test.ts
  __tests__/provider.test.ts
  __tests__/signer.test.ts
  __tests__/utils/__snapshots__/utils.browser.test.ts.snap
  __tests__/utils/__snapshots__/utils.test.ts.snap
  __tests__/utils/ellipticalCurve.test.ts
  __tests__/utils/utils.test.ts
  src/provider/default.ts
  src/signer/default.ts
  src/types.ts
  src/utils/hash.ts
  src/utils/stark.ts
Labels: enhancement, MAJOR

#63 fix: correctly parse structs in Starknet return types
  src/constants.ts
  src/contract.ts
  src/types.ts
Labels: enhancement

#73 Release v2.1.0
  CHANGELOG.md
  __tests__/provider.test.ts
  __tests__/utils/ellipticalCurve.test.ts
  package-lock.json
  package.json
  src/provider/default.ts
  src/types.ts
Labels: release

#74 fix: use urljoin
  package-lock.json
  package.json
  src/provider/default.ts
Labels: bug
